/**
 * All six courses and their modules, from docs/NextNTech-Curriculum-Outline.md.
 * Modules with written lessons come from the approved demo; the rest are "coming soon".
 */
import * as L from "./lessons";
import type { SeedCourse } from "./types";

export const curriculum: SeedCourse[] = [
  {
    key: "frontend",
    slug: "front-end-development",
    title: "Front-End Development",
    summary: "Build what people see. HTML, CSS, JavaScript, React.",
    emoji: "🎨",
    color: "#2EC4B6",
    modules: [
      {
        slug: "html-foundations",
        title: "HTML Foundations",
        lessons: [L.htmlSkeleton],
        outline: [
          "What is the web? Browsers, servers, and pages",
          "The history of HTML — Tim Berners-Lee, 1991, and how the web grew",
          "Your first page: tags, elements, and structure",
          "Old tags vs. new tags (goodbye <font> and <center>, hello HTML5)",
          "Text, headings, lists, and links",
          "Images, audio, and video",
          "Tables and forms",
          "Semantic HTML: <header>, <section>, <article>, <footer>",
          'Project: build your "About Me" page',
        ],
      },
      {
        slug: "css-and-layout",
        title: "CSS & Layout",
        lessons: [L.cssDressing],
        outline: [
          "What CSS does — the clothes of the web",
          "Selectors, colors, and fonts",
          "The box model (margin, border, padding)",
          "Flexbox — arranging things in rows and columns",
          "CSS Grid — full page layouts",
          "Responsive design: making pages work on phones",
          "Transitions and simple animations",
          'Project: style your "About Me" page for phone and desktop',
        ],
      },
      {
        slug: "javascript-basics",
        title: "JavaScript Basics",
        lessons: [L.jsMove],
        outline: [
          "What JavaScript does — the muscles of the web",
          "Variables, numbers, and strings",
          "If/else — teaching the page to decide",
          "Loops — doing things many times",
          "Functions — reusable magic spells",
          "The DOM: changing the page with code",
          "Events: clicks, typing, and scrolling",
          "Project: an interactive quiz game",
        ],
      },
      {
        slug: "react",
        title: "React",
        lessons: [],
        outline: [
          "Why React exists — components as LEGO bricks",
          "JSX and your first component",
          "Props and state",
          "Handling events and forms in React",
          "Lists, keys, and rendering data",
          "Project: rebuild your quiz game in React",
        ],
      },
    ],
  },
  {
    key: "backend",
    slug: "back-end-development",
    title: "Back-End Development",
    summary: "Build what powers apps. Node.js, Express, SQL, PHP & Laravel, CMS.",
    emoji: "⚙️",
    color: "#2A4BAE",
    modules: [
      {
        slug: "nodejs-and-express",
        title: "Node.js & Express",
        lessons: [L.firstServer],
        outline: [
          "What is a server? Front end vs. back end",
          "Node.js: JavaScript outside the browser",
          "Your first Express server and routes",
          "APIs and JSON — how apps talk to each other",
          "Middleware and handling requests",
          "Project: build a jokes API",
        ],
      },
      {
        slug: "databases-and-sql",
        title: "Databases & SQL",
        lessons: [L.talkingToDatabases],
        outline: [
          "What is a database and why apps need one",
          "Tables, rows, and columns",
          "SELECT, INSERT, UPDATE, DELETE",
          "Relationships: connecting tables together",
          "Connecting your Express app to a database",
          "Project: a guestbook that remembers visitors",
        ],
      },
      {
        slug: "php-and-its-frameworks",
        title: "PHP & Its Frameworks",
        lessons: [L.phpBehindTheWeb],
        outline: [
          "PHP: the language that powers most of the web",
          "PHP basics: variables, forms, and includes",
          "Laravel: the modern PHP framework",
          "CodeIgniter: the lightweight alternative",
          "When to choose PHP vs. Node.js",
          "Project: a contact form with Laravel",
        ],
      },
      {
        slug: "cms-wordpress-joomla-drupal",
        title: "CMS: WordPress, Joomla & Drupal",
        lessons: [],
        outline: [
          "What a CMS is and why 40% of the web runs on one",
          "WordPress: themes, plugins, and pages",
          "Joomla and Drupal: how they compare",
          "Customizing a WordPress theme with your HTML/CSS skills",
          "Project: build a small site with WordPress",
        ],
      },
    ],
  },
  {
    key: "fullstack",
    slug: "full-stack-development",
    title: "Full-Stack Development",
    summary: "Combine both sides and ship a complete web application.",
    emoji: "🚀",
    color: "#F5A524",
    modules: [
      {
        slug: "connecting-front-and-back",
        title: "Connecting Front & Back",
        lessons: [L.fetchTwoSides],
        outline: [
          "How React talks to Express (fetch and APIs)",
          "Sending and receiving data",
          "Handling errors kindly",
          "Project: a to-do app with a real database",
        ],
      },
      {
        slug: "auth-and-accounts",
        title: "Auth & Accounts",
        lessons: [L.hashingPasswords],
        outline: [
          "How login works: sessions, tokens, passwords",
          "Never store plain passwords — hashing explained",
          "Social login (Google & friends) in simple terms",
          "Project: add accounts to your to-do app",
        ],
      },
      {
        slug: "deploying-your-app",
        title: "Deploying Your App",
        lessons: [],
        outline: [
          'What "deploying" means — putting your app on the internet',
          "Domains, hosting, and environment variables",
          "Free hosting: Vercel, Railway, Render",
          "Project: put your app live and share the link",
        ],
      },
      {
        slug: "capstone-project",
        title: "Capstone Project",
        lessons: [],
        outline: [
          "Plan it: pick an idea and sketch the pages",
          "Build it: front end + back end + database",
          "Test it and fix bugs",
          "Present it — your first portfolio piece 🎓",
        ],
      },
    ],
  },
  {
    key: "python",
    slug: "python",
    title: "Python: Basic to Advanced",
    summary: "The friendliest first language — from print() to real projects.",
    emoji: "🐍",
    color: "#7C5CD6",
    modules: [
      {
        slug: "python-basics",
        title: "Python Basics",
        lessons: [L.pythonFirstProgram],
        outline: [
          "Why Python is the friendliest first language",
          "print(), input(), and variables",
          "Numbers, strings, and f-strings",
          "If/else decisions",
          "Loops",
          "Project: a number-guessing game",
        ],
      },
      {
        slug: "data-and-logic",
        title: "Data & Logic",
        lessons: [L.pythonLists],
        outline: [
          "Lists and dictionaries",
          "Functions",
          "Reading and writing files",
          "Handling errors with try/except",
          "Project: a personal expense tracker",
        ],
      },
      {
        slug: "advanced-python",
        title: "Advanced Python",
        lessons: [],
        outline: [
          "Classes and objects (OOP, gently)",
          "Modules and pip — using other people's code",
          "Working with APIs and JSON",
          "Virtual environments",
          "Project: a weather app using a real API",
        ],
      },
      {
        slug: "build-with-python",
        title: "Build with Python",
        lessons: [],
        outline: [
          "Flask: Python for the web",
          "Automating boring tasks (files, emails, reports)",
          "A taste of data: pandas and charts",
          "Where Python leads: AI, data science, DevOps",
          "Project: your own Flask mini-site",
        ],
      },
    ],
  },
  {
    key: "mobile",
    slug: "mobile-apps",
    title: "Mobile Apps (Android & iOS)",
    summary: "Turn your skills into apps for phones with React Native & Swift.",
    emoji: "📱",
    color: "#E4572E",
    modules: [
      {
        slug: "mobile-basics",
        title: "Mobile Basics",
        lessons: [L.websitesVsApps],
        outline: ["How phone apps differ from websites", "Native vs. cross-platform", "App stores explained"],
      },
      {
        slug: "react-native",
        title: "React Native",
        lessons: [L.reactNative],
        outline: [
          "Reuse your React skills",
          "Components, navigation, styling",
          "Project: a flashcard study app",
        ],
      },
      {
        slug: "swift-and-ios",
        title: "Swift & iOS",
        lessons: [],
        outline: [
          "Swift basics",
          "SwiftUI views",
          "Project: a simple iPhone counter app",
          "A look at Kotlin for Android",
        ],
      },
      {
        slug: "publish-your-app",
        title: "Publish Your App",
        lessons: [],
        outline: ["Icons and screenshots", "Google Play and App Store submission", "Updates and reviews"],
      },
    ],
  },
  {
    key: "career",
    slug: "careers-and-side-hustles",
    title: "Careers & Side Hustles",
    summary: "Fiverr, Upwork, Freelancer, remote jobs — earn with your skills.",
    emoji: "💼",
    color: "#2E933C",
    modules: [
      {
        slug: "your-portfolio",
        title: "Your Portfolio",
        lessons: [L.portfolio],
        outline: ["GitHub", "A portfolio site (you can build one now!)", "Telling your story"],
      },
      {
        slug: "freelance-platforms",
        title: "Freelance Platforms",
        lessons: [L.freelancePlatforms],
        outline: [
          "Fiverr, Upwork, and Freelancer",
          "Profiles, gigs, and first proposals",
          "Fair pricing",
          "Avoiding scams",
        ],
      },
      {
        slug: "remote-jobs",
        title: "Remote Jobs",
        lessons: [],
        outline: [
          "Where to find them (LinkedIn, remote job boards)",
          "Junior-friendly roles",
          "Resumes and interviews for young developers",
        ],
      },
      {
        slug: "working-with-clients",
        title: "Working with Clients",
        lessons: [],
        outline: [
          "Communication, deadlines, and revisions",
          "Getting paid safely",
          "Growing from side hustle to career",
        ],
      },
    ],
  },
];
